### ISSUE TITLE
Cannot see the device as a host!

### ISSUE THREAD

**Issue by wiledal** [cmengler/fitbit-app-versa4#4]
I just got my Versa 4 and was super stoked to use the SDK to built my own watch faces. 
Was crushed when I found out they don't support Versa 4 - what a weird move from Fitbit (I guess Google?).

I'm trying the guidelines laid out in this article but I cannot see my Versa 4 as a host, though I see it in my list of connected USB devices.
<img width="343" alt="Screenshot 2023-08-25 at 16 56 10" src="https://github.com/cmengler/fitbit-app-versa4/assets/1035169/9e3cbe16-9d20-4ef9-b61b-2e7edd1c7136">

Any ideas?
Thanks for doing this btw. I hope I get it working.

**Comment by wiledal** [comment]
Okay, so I dug into the https://github.com/Fitbit/developer-bridge repo and it all looks like it should be working. 
Instead of pulling from npm, I tried installing from source, and voila - I see my device!
Unclear why it doesn't work from npm, but this workaround is fine.

**Comment by wiledal** [comment]
Ah I'm stupid, I just noticed this repo uses pre-releases of the fitbit sdk. Makes me even more sad that they discontinued this. Thanks so much for this!

I put this quick watchface together to test it out!

![PXL_20230825_170448636](https://github.com/cmengler/fitbit-app-versa4/assets/1035169/9e083a58-a79b-449c-8b0b-4c5f7235145c)

**Comment by jkmartindale** [comment]
How do you install from source?

**Comment by wiledal** [comment]
@jkmartindale If you pull this repo and use it as a starting point, follow all the instructions, everything should work as expected.

Custom watch faces are technically not supported tho, so the watch gets into a weird state when you do it.

I ended up using FitFace instead: https://fitface.xyz/.
Install once, design in a simple web interface.

**Comment by jkmartindale** [comment]
Ah yeah I figured it out. I got a bit confused and thought this was related to a libusb error I was getting on Windows but that ended up being something separate. If anyone else comes across this, I used https://visualgdb.com/UsbDriverTool/

Thanks for the heads up about the weird state from custom watch faces. I wasn't able to swap to a first-party watch face from my dev watch face without a factory reset, so I guess that's "normal" and not just a one-off thing.

**Comment by lardahle** [comment]
@jkmartindale howdy! Was curious what driver type you ended up getting to work? Im trying to sideload on my Sense 2 and can't get it to show up in the hosts for the life of me; I've tried the USBDriverTool mentioned with all available driver types to no avail but am unaware if any additional steps were required.

**Comment by jkmartindale** [comment]
> @jkmartindale howdy! Was curious what driver type you ended up getting to work? Im trying to sideload on my Sense 2 and can't get it to show up in the hosts for the life of me; I've tried the USBDriverTool mentioned with all available driver types to no avail but am unaware if any additional steps were required.

I used a LibUSB driver I'm pretty sure. Can't remember what additional steps there were (if any) because I haven't touched Fitbit dev for over a year.

**Comment by lardahle** [comment]
> > @jkmartindale howdy! Was curious what driver type you ended up getting to work? Im trying to sideload on my Sense 2 and can't get it to show up in the hosts for the life of me; I've tried the USBDriverTool mentioned with all available driver types to no avail but am unaware if any additional steps were required.
> 
> I used a LibUSB driver I'm pretty sure. Can't remember what additional steps there were (if any) because I haven't touched Fitbit dev for over a year.

Thank you for the quick response regardless! I will keep at it with that in mind.

**Comment by EddieFed** [comment]
> > 
> > 
> > I used a LibUSB driver I'm pretty sure. Can't remember what additional steps there were (if any) because I haven't touched Fitbit dev for over a year.
> 
> Thank you for the quick response regardless! I will keep at it with that in mind.

~~@lardahle Hi! I'm just trying to toy around with this myself with my Versa 4! Did you ever manage to figure this out? I've tried using zadig to set the driver but nothing has come from it. If i leave the default libusb0 driver, the hosts command throws an error. But if I load any other driver (WinUSB, libusbK, etc), this fixed my error but no target shows up under hosts!~~

I did manage to get it working! Couple things to note, first of all, using [zadig](https://github.com/pbatard/libwdi) and loading a generic WinUSB driver (WinUSB v6.1.7600.16385) *did* work. And second, I was simply being dumb and I didn't have the developer bridge+usb debugging enabled. Duh!

**Comment by lardahle** [comment]
@EddieFed so sorry for being MIA; just finished my last project in engineering school!!! Was a big crunch and I had to lock out of everything else. Onto the next thing though; hopefully at one point that can be getting back into fitbit dev :)
