### ISSUE TITLE
Update - Works on Sense 2!

### ISSUE THREAD

**Issue by eraykoschell** [cmengler/fitbit-app-versa4#7]
I was recently looking into developing an app for Fitbit until the sudden realisation there's no official way to develop one for a Sense 2.

I came across this repo and decided to try it and wanted to say that **this works on a Sense 2**. Noticed it says 'possibly works on Sense 2' so hopefully you can rename/change repo accordingly.

Created a simple cookie clicker, screenshots below:

| App List | App |
|-|-|
![App List](https://github.com/cmengler/fitbit-app-versa4/assets/44278658/34ff577a-726b-40e0-a471-ed3ca90b1377) | ![Cookie Clicker](https://github.com/cmengler/fitbit-app-versa4/assets/44278658/b9f186e7-001f-40b8-bea1-5a16f3592bd4)

**Comment by cmengler** [comment]
Awesome work! I'll update the repo description -- Thanks for confirming this @eraychumak 👍

**Comment by amasterson1** [comment]
@eraychumak How did you go about connecting your Sense 2? I seem to be unable to have it recognized in the hosts command. Even after changing USB driver types.
